name: publish
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  publish-hello-dash-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build hello-dash Docker image
        run: |
          docker build . --tag ghcr.io/changeroot/hello-dash:latest
          docker push ghcr.io/changeroot/hello-dash:latest